# Generated by Django 5.2.6 on 2025-09-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_quizquestion_userprofile_quizresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='user',
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='title',
            field=models.CharField(default='New Chat', max_length=255),
        ),
    ]
